"
may be one day....

Asimov, Isaac  :
- books : optional tag
-- nemesis 2,69
-- le voyage fantastique 2,39
- foundation : a great series
-- Fondation 
-- Second fondation 2,69
- another book outside the two first section


what about multi lines
  
Asimov, Isaac  :
- books : optional tag
-- nemesis 2,69
lklkkjkjkkjk
jkljkjl
-- le voyage fantastique 2,39
- Foundation : a great series
-- Fondation 
-- Second fondation 2,69
- another book outside the two first section


What about properties
  
Asimov, Isaac  :
- books :
-- nemesis (price: 2.69, format: large, lu: true, ...)
-- title: le voyage fantastique, price: 2.39, format: small, lu: false, status: moyen

"
Class {
	#name : #PPStrotesGrammar,
	#superclass : #PPCompositeParser,
	#category : #'Collector-Easy-NotStarted'
}
