"
I'm a simple emtpy visitor. I visit books, author, collection and serie.
"
Class {
	#name : #CSimpleBookVisitor,
	#superclass : #Object,
	#category : #'Collector-SimpleBooks-Operations'
}

{ #category : #visiting }
CSimpleBookVisitor >> visitAuthor: anAuthor [
	
]

{ #category : #visiting }
CSimpleBookVisitor >> visitBook: aBookItem [

	
]

{ #category : #visiting }
CSimpleBookVisitor >> visitCollection: aCollection [
	
]

{ #category : #visiting }
CSimpleBookVisitor >> visitSerie: aSerieItem [

	
]
